import type { Metadata } from 'next';
import Link from 'next/link';
import { Logo } from '@/components/logo';

export const metadata: Metadata = {
  title: 'Disclaimer | QueryAI by SamaBrains',
  description: 'Disclaimer for QueryAI – informational use only, no professional advice. SamaBrains Solution Company, Kampala, Uganda.',
  openGraph: {
    title: 'Disclaimer | QueryAI by SamaBrains',
    description: 'Disclaimer for QueryAI – informational use only, no professional advice.',
  },
};

export default function DisclaimerPage() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-orange-50">
      <nav className="bg-white/80 backdrop-blur-sm shadow-sm sticky top-0 z-50">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between h-16 items-center">
            <Logo href="/" showName size="sm" />
            <Link href="/" className="text-sm text-gray-600 hover:text-gray-900">Back to Home</Link>
          </div>
        </div>
      </nav>

      <main className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <h1 className="text-4xl font-bold text-gray-900 mb-2">Disclaimer</h1>
        <p className="text-sm text-gray-500 mb-8">
          QueryAI by SamaBrains Solution Company · Kampala, Uganda
        </p>

        <div className="rounded-lg border border-amber-200 bg-amber-50 p-4 mb-8 text-amber-900">
          <p className="font-medium">
            QueryAI provides AI-assisted research and source-cited answers for informational purposes only. It does not constitute professional, legal, medical, financial, or other advice. Always verify critical information with qualified professionals and primary sources.
          </p>
        </div>

        <div className="prose prose-gray max-w-none space-y-6 text-gray-700">
          <section>
            <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-2">1. No Professional Advice</h2>
            <p>
              Content and answers generated by QueryAI are for general information and research assistance only. They are not a substitute for professional advice from qualified experts in law, medicine, finance, tax, or other fields. Do not rely on QueryAI output for decisions that could affect your health, legal rights, or finances without consulting an appropriate professional.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-2">2. Accuracy and Sources</h2>
            <p>
              We strive to surface relevant sources and cite them where possible. However, we do not guarantee the accuracy, completeness, or timeliness of any information. Sources may be outdated, biased, or incorrect. You are responsible for evaluating and verifying any information before using it.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-2">3. AI-Generated Content</h2>
            <p>
              QueryAI uses artificial intelligence and external search/document inputs to generate responses. AI can make errors, omit context, or reflect biases present in training or retrieved data. Use your judgment and cross-check important facts.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-2">4. Your Responsibility</h2>
            <p>
              You are solely responsible for how you use QueryAI and any decisions you make based on its output. SamaBrains Solution Company and its affiliates are not liable for any loss or damage arising from your use of or reliance on the Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-2">5. Third-Party Content</h2>
            <p>
              QueryAI may reference or link to third-party websites and content. We do not control or endorse such content and are not responsible for its accuracy or legality. Accessing third-party content is at your own risk.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-2">6. Contact</h2>
            <p>
              For questions about this disclaimer or QueryAI, contact SamaBrains Solution Company at <a href="mailto:info@samabrain.com" className="text-blue-600 hover:underline">info@samabrain.com</a>. We are based in Kampala, Uganda.
            </p>
          </section>
        </div>

        <div className="mt-12 pt-8 border-t border-gray-200 flex flex-wrap gap-4 text-sm">
          <Link href="/privacy" className="text-blue-600 hover:underline">Privacy Policy</Link>
          <Link href="/cookie-policy" className="text-blue-600 hover:underline">Cookies</Link>
          <Link href="/terms" className="text-blue-600 hover:underline">Terms of Service</Link>
          <Link href="/" className="text-blue-600 hover:underline">Home</Link>
        </div>
      </main>
    </div>
  );
}
